name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for issueing a message. We appreciate your efforts and will respond as quickly as possible.'' first issue'
        pr-message: 'It was so nice to help us finished this project. Thank you for reaching out.'' first pr'
